from typing_extensions import Any, Dict, Protocol


class IServerContext(Protocol):
    @property
    def grpc_server(self) -> Any: ...

    def register_service_event(self, service_name: str) -> None: ...


class IServerPlugin(Protocol):
    def configure(self, context: IServerContext, settings: Dict[str, Any]) -> None: ...
    def on_add_service(self, service_name: str) -> None: ...
    def on_start(self) -> None: ...
