"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class InnerMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AGE_FIELD_NUMBER: builtins.int
    age: builtins.int
    def __init__(
        self,
        *,
        age: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["age", b"age"]) -> None: ...

global___InnerMessage = InnerMessage
