# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpcapi/protobuf/types.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 0, "", "grpcapi/protobuf/types.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1cgrpcapi/protobuf/types.proto\x12\x10grpcAPI.protobuf"\x18\n\x07ListStr\x12\r\n\x05value\x18\x01 \x03(\t"\x18\n\x07ListInt\x12\r\n\x05value\x18\x01 \x03(\x03"\x19\n\x08ListBool\x12\r\n\x05value\x18\x01 \x03(\x08"\x1a\n\tListBytes\x12\r\n\x05value\x18\x01 \x03(\x0c"\x1b\n\nListDouble\x12\r\n\x05value\x18\x01 \x03(\x01"p\n\tMapStrStr\x12\x35\n\x05value\x18\x01 \x03(\x0b\x32&.grpcAPI.protobuf.MapStrStr.ValueEntry\x1a,\n\nValueEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"t\n\x0bMapStrBytes\x12\x37\n\x05value\x18\x01 \x03(\x0b\x32(.grpcAPI.protobuf.MapStrBytes.ValueEntry\x1a,\n\nValueEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01"p\n\tMapIntStr\x12\x35\n\x05value\x18\x01 \x03(\x0b\x32&.grpcAPI.protobuf.MapIntStr.ValueEntry\x1a,\n\nValueEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"t\n\x0bMapIntBytes\x12\x37\n\x05value\x18\x01 \x03(\x0b\x32(.grpcAPI.protobuf.MapIntBytes.ValueEntry\x1a,\n\nValueEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01")\n\x0bKeyValueStr\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\tBj\n\x14\x63om.grpcAPI.protobufB\nTypesProtoP\x01Z$grpcAPI.golang.org/protobuf/protobuf\xf8\x01\x01\xa2\x02\x07GRPCAPI\xaa\x02\x10grpcAPI.protobufb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "grpcapi.protobuf.types_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"\n\024com.grpcAPI.protobufB\nTypesProtoP\001Z$grpcAPI.golang.org/protobuf/protobuf\370\001\001\242\002\007GRPCAPI\252\002\020grpcAPI.protobuf"
    )
    _globals["_MAPSTRSTR_VALUEENTRY"]._loaded_options = None
    _globals["_MAPSTRSTR_VALUEENTRY"]._serialized_options = b"8\001"
    _globals["_MAPSTRBYTES_VALUEENTRY"]._loaded_options = None
    _globals["_MAPSTRBYTES_VALUEENTRY"]._serialized_options = b"8\001"
    _globals["_MAPINTSTR_VALUEENTRY"]._loaded_options = None
    _globals["_MAPINTSTR_VALUEENTRY"]._serialized_options = b"8\001"
    _globals["_MAPINTBYTES_VALUEENTRY"]._loaded_options = None
    _globals["_MAPINTBYTES_VALUEENTRY"]._serialized_options = b"8\001"
    _globals["_LISTSTR"]._serialized_start = 50
    _globals["_LISTSTR"]._serialized_end = 74
    _globals["_LISTINT"]._serialized_start = 76
    _globals["_LISTINT"]._serialized_end = 100
    _globals["_LISTBOOL"]._serialized_start = 102
    _globals["_LISTBOOL"]._serialized_end = 127
    _globals["_LISTBYTES"]._serialized_start = 129
    _globals["_LISTBYTES"]._serialized_end = 155
    _globals["_LISTDOUBLE"]._serialized_start = 157
    _globals["_LISTDOUBLE"]._serialized_end = 184
    _globals["_MAPSTRSTR"]._serialized_start = 186
    _globals["_MAPSTRSTR"]._serialized_end = 298
    _globals["_MAPSTRSTR_VALUEENTRY"]._serialized_start = 254
    _globals["_MAPSTRSTR_VALUEENTRY"]._serialized_end = 298
    _globals["_MAPSTRBYTES"]._serialized_start = 300
    _globals["_MAPSTRBYTES"]._serialized_end = 416
    _globals["_MAPSTRBYTES_VALUEENTRY"]._serialized_start = 372
    _globals["_MAPSTRBYTES_VALUEENTRY"]._serialized_end = 416
    _globals["_MAPINTSTR"]._serialized_start = 418
    _globals["_MAPINTSTR"]._serialized_end = 530
    _globals["_MAPINTSTR_VALUEENTRY"]._serialized_start = 486
    _globals["_MAPINTSTR_VALUEENTRY"]._serialized_end = 530
    _globals["_MAPINTBYTES"]._serialized_start = 532
    _globals["_MAPINTBYTES"]._serialized_end = 648
    _globals["_MAPINTBYTES_VALUEENTRY"]._serialized_start = 604
    _globals["_MAPINTBYTES_VALUEENTRY"]._serialized_end = 648
    _globals["_KEYVALUESTR"]._serialized_start = 650
    _globals["_KEYVALUESTR"]._serialized_end = 691
# @@protoc_insertion_point(module_scope)
