"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class AccountInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    CPF_FIELD_NUMBER: builtins.int
    CAR_PLATE_FIELD_NUMBER: builtins.int
    IS_DRIVER_FIELD_NUMBER: builtins.int
    name: builtins.str
    email: builtins.str
    cpf: builtins.str
    car_plate: builtins.str
    is_driver: builtins.bool
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        email: builtins.str = ...,
        cpf: builtins.str = ...,
        car_plate: builtins.str = ...,
        is_driver: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["car_plate", b"car_plate", "cpf", b"cpf", "email", b"email", "is_driver", b"is_driver", "name", b"name"]) -> None: ...

global___AccountInfo = AccountInfo

@typing.final
class Account(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    account_id: builtins.str
    @property
    def info(self) -> global___AccountInfo: ...
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        account_id: builtins.str = ...,
        info: global___AccountInfo | None = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["created_at", b"created_at", "info", b"info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["account_id", b"account_id", "created_at", b"created_at", "info", b"info"]) -> None: ...

global___Account = Account
