# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pack1/mod1.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'pack1/mod1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10pack1/mod1.proto\x12\x05pack1\":\n\tUserNames\x12\x0b\n\x03ids\x18\x01 \x03(\x03\x12\x12\n\x08\x65mployee\x18\x02 \x01(\tH\x00\x42\x0c\n\noccupation\"\xb9\x01\n\x04User\x12(\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x0f.pack1.UserCodeR\tuser_code\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x03\x12\x14\n\x0c\x61\x66\x66illiation\x18\x03 \x01(\t\x12\x10\n\x04name\x18\x04 \x01(\tB\x02\x18\x01\x12\n\n\x02id\x18\x05 \x01(\t\x12\x12\n\x08\x65mployee\x18\x06 \x01(\tH\x00\x12\x10\n\x06school\x18\x07 \x01(\tH\x00\x12\x12\n\x08inactive\x18\x08 \x01(\x08H\x00\x42\x0c\n\noccupation\"5\n\x08UserList\x12\x1a\n\x05users\x18\x01 \x03(\x0b\x32\x0b.pack1.User\x12\r\n\x05index\x18\x0c \x01(\x05\"j\n\tUserInput\x12(\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x0f.pack1.UserCodeR\tuser_code\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x03\x12\x14\n\x0c\x61\x66\x66illiation\x18\x03 \x01(\t\x12\x10\n\x04name\x18\x04 \x01(\tB\x02\x18\x01*;\n\x08UserCode\x12\x0c\n\x08\x45MPLOYEE\x10\x00\x12\x13\n\x06SCHOOL\x10\x89\xfe\xff\xff\xff\xff\xff\xff\xff\x01\x12\x0c\n\x08INACTIVE\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pack1.mod1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER'].fields_by_name['name']._loaded_options = None
  _globals['_USER'].fields_by_name['name']._serialized_options = b'\030\001'
  _globals['_USERINPUT'].fields_by_name['name']._loaded_options = None
  _globals['_USERINPUT'].fields_by_name['name']._serialized_options = b'\030\001'
  _globals['_USERCODE']._serialized_start=438
  _globals['_USERCODE']._serialized_end=497
  _globals['_USERNAMES']._serialized_start=27
  _globals['_USERNAMES']._serialized_end=85
  _globals['_USER']._serialized_start=88
  _globals['_USER']._serialized_end=273
  _globals['_USERLIST']._serialized_start=275
  _globals['_USERLIST']._serialized_end=328
  _globals['_USERINPUT']._serialized_start=330
  _globals['_USERINPUT']._serialized_end=436
# @@protoc_insertion_point(module_scope)
