# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ride/ride_proto.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ride/ride_proto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15ride/ride_proto.proto\x12\x04ride\x1a\x1fgoogle/protobuf/timestamp.proto\"\"\n\x05\x43oord\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0c\n\x04long\x18\x02 \x01(\x01\"\x97\x01\n\x0bRideRequest\x12\x14\n\x0cpassenger_id\x18\x01 \x01(\t\x12 \n\x0bstart_point\x18\x02 \x01(\x0b\x32\x0b.ride.Coord\x12\x1e\n\tend_point\x18\x03 \x01(\x0b\x32\x0b.ride.Coord\x12\x30\n\x0crequested_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xa9\x02\n\x04Ride\x12\x0f\n\x07ride_id\x18\x01 \x01(\t\x12\x14\n\x0cpassenger_id\x18\x02 \x01(\t\x12\x11\n\tdriver_id\x18\x03 \x01(\t\x12 \n\x0bstart_point\x18\x04 \x01(\x0b\x32\x0b.ride.Coord\x12\x1e\n\tend_point\x18\x05 \x01(\x0b\x32\x0b.ride.Coord\x12\x0c\n\x04\x66\x61re\x18\x06 \x01(\x02\x12/\n\x0b\x61\x63\x63\x65pted_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x34\n\x0b\x66inished_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x88\x01\x01\x12 \n\x06status\x18\t \x01(\x0e\x32\x10.ride.RideStatusB\x0e\n\x0c_finished_at\"l\n\x0cRideSnapshot\x12\x18\n\x04ride\x18\x01 \x01(\x0b\x32\n.ride.Ride\x12-\n\x10\x63urrent_location\x18\x02 \x01(\x0b\x32\x0e.ride.PositionH\x00\x88\x01\x01\x42\x13\n\x11_current_location\"g\n\x08Position\x12\x0f\n\x07ride_id\x18\x01 \x01(\t\x12\x1a\n\x05\x63oord\x18\x02 \x01(\x0b\x32\x0b.ride.Coord\x12.\n\nupdated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*W\n\nRideStatus\x12\r\n\tREQUESTED\x10\x00\x12\x0c\n\x08\x41\x43\x43\x45PTED\x10\x01\x12\x0f\n\x0bIN_PROGRESS\x10\x02\x12\r\n\tCOMPLETED\x10\x03\x12\x0c\n\x08\x43\x41NCELED\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ride.ride_proto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RIDESTATUS']._serialized_start=769
  _globals['_RIDESTATUS']._serialized_end=856
  _globals['_COORD']._serialized_start=64
  _globals['_COORD']._serialized_end=98
  _globals['_RIDEREQUEST']._serialized_start=101
  _globals['_RIDEREQUEST']._serialized_end=252
  _globals['_RIDE']._serialized_start=255
  _globals['_RIDE']._serialized_end=552
  _globals['_RIDESNAPSHOT']._serialized_start=554
  _globals['_RIDESNAPSHOT']._serialized_end=662
  _globals['_POSITION']._serialized_start=664
  _globals['_POSITION']._serialized_end=767
# @@protoc_insertion_point(module_scope)
