"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _RideStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _RideStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RideStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    REQUESTED: _RideStatus.ValueType  # 0
    ACCEPTED: _RideStatus.ValueType  # 1
    IN_PROGRESS: _RideStatus.ValueType  # 2
    COMPLETED: _RideStatus.ValueType  # 3
    CANCELED: _RideStatus.ValueType  # 4

class RideStatus(_RideStatus, metaclass=_RideStatusEnumTypeWrapper): ...

REQUESTED: RideStatus.ValueType  # 0
ACCEPTED: RideStatus.ValueType  # 1
IN_PROGRESS: RideStatus.ValueType  # 2
COMPLETED: RideStatus.ValueType  # 3
CANCELED: RideStatus.ValueType  # 4
global___RideStatus = RideStatus

@typing.final
class Coord(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LAT_FIELD_NUMBER: builtins.int
    LONG_FIELD_NUMBER: builtins.int
    lat: builtins.float
    long: builtins.float
    def __init__(
        self,
        *,
        lat: builtins.float = ...,
        long: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["lat", b"lat", "long", b"long"]) -> None: ...

global___Coord = Coord

@typing.final
class RideRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PASSENGER_ID_FIELD_NUMBER: builtins.int
    START_POINT_FIELD_NUMBER: builtins.int
    END_POINT_FIELD_NUMBER: builtins.int
    REQUESTED_AT_FIELD_NUMBER: builtins.int
    passenger_id: builtins.str
    @property
    def start_point(self) -> global___Coord: ...
    @property
    def end_point(self) -> global___Coord: ...
    @property
    def requested_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        passenger_id: builtins.str = ...,
        start_point: global___Coord | None = ...,
        end_point: global___Coord | None = ...,
        requested_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["end_point", b"end_point", "requested_at", b"requested_at", "start_point", b"start_point"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["end_point", b"end_point", "passenger_id", b"passenger_id", "requested_at", b"requested_at", "start_point", b"start_point"]) -> None: ...

global___RideRequest = RideRequest

@typing.final
class Ride(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RIDE_ID_FIELD_NUMBER: builtins.int
    PASSENGER_ID_FIELD_NUMBER: builtins.int
    DRIVER_ID_FIELD_NUMBER: builtins.int
    START_POINT_FIELD_NUMBER: builtins.int
    END_POINT_FIELD_NUMBER: builtins.int
    FARE_FIELD_NUMBER: builtins.int
    ACCEPTED_AT_FIELD_NUMBER: builtins.int
    FINISHED_AT_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    ride_id: builtins.str
    passenger_id: builtins.str
    driver_id: builtins.str
    fare: builtins.float
    status: global___RideStatus.ValueType
    @property
    def start_point(self) -> global___Coord: ...
    @property
    def end_point(self) -> global___Coord: ...
    @property
    def accepted_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def finished_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        ride_id: builtins.str = ...,
        passenger_id: builtins.str = ...,
        driver_id: builtins.str = ...,
        start_point: global___Coord | None = ...,
        end_point: global___Coord | None = ...,
        fare: builtins.float = ...,
        accepted_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        finished_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        status: global___RideStatus.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_finished_at", b"_finished_at", "accepted_at", b"accepted_at", "end_point", b"end_point", "finished_at", b"finished_at", "start_point", b"start_point"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_finished_at", b"_finished_at", "accepted_at", b"accepted_at", "driver_id", b"driver_id", "end_point", b"end_point", "fare", b"fare", "finished_at", b"finished_at", "passenger_id", b"passenger_id", "ride_id", b"ride_id", "start_point", b"start_point", "status", b"status"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_finished_at", b"_finished_at"]) -> typing.Literal["finished_at"] | None: ...

global___Ride = Ride

@typing.final
class RideSnapshot(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RIDE_FIELD_NUMBER: builtins.int
    CURRENT_LOCATION_FIELD_NUMBER: builtins.int
    @property
    def ride(self) -> global___Ride: ...
    @property
    def current_location(self) -> global___Position: ...
    def __init__(
        self,
        *,
        ride: global___Ride | None = ...,
        current_location: global___Position | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_current_location", b"_current_location", "current_location", b"current_location", "ride", b"ride"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_current_location", b"_current_location", "current_location", b"current_location", "ride", b"ride"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_current_location", b"_current_location"]) -> typing.Literal["current_location"] | None: ...

global___RideSnapshot = RideSnapshot

@typing.final
class Position(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RIDE_ID_FIELD_NUMBER: builtins.int
    COORD_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    ride_id: builtins.str
    @property
    def coord(self) -> global___Coord: ...
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        ride_id: builtins.str = ...,
        coord: global___Coord | None = ...,
        updated_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["coord", b"coord", "updated_at", b"updated_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["coord", b"coord", "ride_id", b"ride_id", "updated_at", b"updated_at"]) -> None: ...

global___Position = Position
