"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _RideStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _RideStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RideStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    REQUESTED: _RideStatus.ValueType  # 0
    ACCEPTED: _RideStatus.ValueType  # 1
    IN_PROGRESS: _RideStatus.ValueType  # 2
    COMPLETED: _RideStatus.ValueType  # 3
    CANCELED: _RideStatus.ValueType  # 4

class RideStatus(_RideStatus, metaclass=_RideStatusEnumTypeWrapper): ...

REQUESTED: RideStatus.ValueType  # 0
ACCEPTED: RideStatus.ValueType  # 1
IN_PROGRESS: RideStatus.ValueType  # 2
COMPLETED: RideStatus.ValueType  # 3
CANCELED: RideStatus.ValueType  # 4
global___RideStatus = RideStatus

@typing.final
class RideRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PASSENGER_ID_FIELD_NUMBER: builtins.int
    FROM_LAT_FIELD_NUMBER: builtins.int
    FROM_LONG_FIELD_NUMBER: builtins.int
    TO_LAT_FIELD_NUMBER: builtins.int
    TO_LONG_FIELD_NUMBER: builtins.int
    REQUESTED_AT_FIELD_NUMBER: builtins.int
    passenger_id: builtins.str
    from_lat: builtins.float
    from_long: builtins.float
    to_lat: builtins.float
    to_long: builtins.float
    @property
    def requested_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        passenger_id: builtins.str = ...,
        from_lat: builtins.float = ...,
        from_long: builtins.float = ...,
        to_lat: builtins.float = ...,
        to_long: builtins.float = ...,
        requested_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["requested_at", b"requested_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["from_lat", b"from_lat", "from_long", b"from_long", "passenger_id", b"passenger_id", "requested_at", b"requested_at", "to_lat", b"to_lat", "to_long", b"to_long"]) -> None: ...

global___RideRequest = RideRequest

@typing.final
class RideInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DRIVER_ID_FIELD_NUMBER: builtins.int
    RIDE_REQUEST_FIELD_NUMBER: builtins.int
    RIDE_ID_FIELD_NUMBER: builtins.int
    ACCEPTED_AT_FIELD_NUMBER: builtins.int
    FINISHED_AT_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    driver_id: builtins.str
    ride_id: builtins.str
    status: global___RideStatus.ValueType
    @property
    def ride_request(self) -> global___RideRequest: ...
    @property
    def accepted_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def finished_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        driver_id: builtins.str = ...,
        ride_request: global___RideRequest | None = ...,
        ride_id: builtins.str = ...,
        accepted_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        finished_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        status: global___RideStatus.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_finished_at", b"_finished_at", "accepted_at", b"accepted_at", "finished_at", b"finished_at", "ride_request", b"ride_request"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_finished_at", b"_finished_at", "accepted_at", b"accepted_at", "driver_id", b"driver_id", "finished_at", b"finished_at", "ride_id", b"ride_id", "ride_request", b"ride_request", "status", b"status"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_finished_at", b"_finished_at"]) -> typing.Literal["finished_at"] | None: ...

global___RideInfo = RideInfo
