# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fail.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'fail.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfail.proto\"\x14\n\x04\x43ode\x12\x0c\n\x04\x43ode\x18\x01 \x01(\x03\"\x15\n\x05Hello\x12\x0c\n\x04\x43ode\x18\x01 \x01(\x03*+\n\x02\x45\x31\x12\x08\n\x04\x63ode\x10\x00\x12\x10\n\x03our\x10\x91\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\t\n\x05outro\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fail_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_E1']._serialized_start=59
  _globals['_E1']._serialized_end=102
  _globals['_CODE']._serialized_start=14
  _globals['_CODE']._serialized_end=34
  _globals['_HELLO']._serialized_start=36
  _globals['_HELLO']._serialized_end=57
# @@protoc_insertion_point(module_scope)
