# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"f\n\nuser_input\x12#\n\x04\x63ode\x18\x01 \x01(\x0e\x32\n.user_codeR\tuser_code\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x03\x12\x10\n\x04name\x18\x04 \x01(\tB\x02\x18\x01\x12\x14\n\x0c\x61\x66\x66illiation\x18\x05 \x01(\t\"y\n\x04user\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x03\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x10\n\x04name\x18\x04 \x01(\tB\x02\x18\x01\x12\x12\n\x08\x65mployee\x18\x05 \x01(\tH\x00\x12\x10\n\x06school\x18\x06 \x01(\tH\x00\x12\x12\n\x08inactive\x18\x07 \x01(\x08H\x00\x42\x0c\n\noccupation\"0\n\tuser_list\x12\x14\n\x05users\x18\x01 \x03(\x0b\x32\x05.user\x12\r\n\x05index\x18\x0c \x01(\x05\"\x17\n\x08names_id\x12\x0b\n\x03ids\x18\x01 \x03(\x05*<\n\tuser_code\x12\x0c\n\x08\x45MPLOYEE\x10\x00\x12\x13\n\x06SCHOOL\x10\x89\xfe\xff\xff\xff\xff\xff\xff\xff\x01\x12\x0c\n\x08INACTIVE\x10\x01\x32\xa3\x01\n\x0cuser_service\x12\x1d\n\x07newuser\x12\x0b.user_input\x1a\x05.user\x12(\n\x0bmanynewuser\x12\x0b.user_input\x1a\n.user_list(\x01\x12\x1e\n\x08getusers\x12\t.names_id\x1a\x05.user0\x01\x12*\n\x10\x62ilateralnewuser\x12\x0b.user_input\x1a\x05.user(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER_INPUT'].fields_by_name['name']._loaded_options = None
  _globals['_USER_INPUT'].fields_by_name['name']._serialized_options = b'\030\001'
  _globals['_USER'].fields_by_name['name']._loaded_options = None
  _globals['_USER'].fields_by_name['name']._serialized_options = b'\030\001'
  _globals['_USER_CODE']._serialized_start=319
  _globals['_USER_CODE']._serialized_end=379
  _globals['_USER_INPUT']._serialized_start=17
  _globals['_USER_INPUT']._serialized_end=119
  _globals['_USER']._serialized_start=121
  _globals['_USER']._serialized_end=242
  _globals['_USER_LIST']._serialized_start=244
  _globals['_USER_LIST']._serialized_end=292
  _globals['_NAMES_ID']._serialized_start=294
  _globals['_NAMES_ID']._serialized_end=317
  _globals['_USER_SERVICE']._serialized_start=382
  _globals['_USER_SERVICE']._serialized_end=545
# @@protoc_insertion_point(module_scope)
