# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc

from . import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = "1.71.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class user_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.newuser = channel.unary_unary(
            "/user_service/newuser",
            request_serializer=service__pb2.user_input.SerializeToString,
            response_deserializer=service__pb2.user.FromString,
            _registered_method=True,
        )
        self.manynewuser = channel.stream_unary(
            "/user_service/manynewuser",
            request_serializer=service__pb2.user_input.SerializeToString,
            response_deserializer=service__pb2.user_list.FromString,
            _registered_method=True,
        )
        self.getusers = channel.unary_stream(
            "/user_service/getusers",
            request_serializer=service__pb2.names_id.SerializeToString,
            response_deserializer=service__pb2.user.FromString,
            _registered_method=True,
        )
        self.bilateralnewuser = channel.stream_stream(
            "/user_service/bilateralnewuser",
            request_serializer=service__pb2.user_input.SerializeToString,
            response_deserializer=service__pb2.user.FromString,
            _registered_method=True,
        )


class user_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def newuser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def manynewuser(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def getusers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def bilateralnewuser(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_user_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "newuser": grpc.unary_unary_rpc_method_handler(
            servicer.newuser,
            request_deserializer=service__pb2.user_input.FromString,
            response_serializer=service__pb2.user.SerializeToString,
        ),
        "manynewuser": grpc.stream_unary_rpc_method_handler(
            servicer.manynewuser,
            request_deserializer=service__pb2.user_input.FromString,
            response_serializer=service__pb2.user_list.SerializeToString,
        ),
        "getusers": grpc.unary_stream_rpc_method_handler(
            servicer.getusers,
            request_deserializer=service__pb2.names_id.FromString,
            response_serializer=service__pb2.user.SerializeToString,
        ),
        "bilateralnewuser": grpc.stream_stream_rpc_method_handler(
            servicer.bilateralnewuser,
            request_deserializer=service__pb2.user_input.FromString,
            response_serializer=service__pb2.user.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "user_service", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("user_service", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class user_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def newuser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/user_service/newuser",
            service__pb2.user_input.SerializeToString,
            service__pb2.user.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def manynewuser(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            "/user_service/manynewuser",
            service__pb2.user_input.SerializeToString,
            service__pb2.user_list.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def getusers(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/user_service/getusers",
            service__pb2.names_id.SerializeToString,
            service__pb2.user.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def bilateralnewuser(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/user_service/bilateralnewuser",
            service__pb2.user_input.SerializeToString,
            service__pb2.user.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
