# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: teste2.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "teste2.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cteste2.proto"\x10\n\x02ID\x12\n\n\x02id\x18\x01 \x01(\x03"\xa7\x01\n\x04\x43ode\x12\x19\n\x02me\x18\x01 \x03(\x0b\x32\r.Code.MeEntry\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x03\x12\x18\n\x02pa\x18\x13 \x01(\x0e\x32\x0c.ProductArea\x12\t\n\x01s\x18\x14 \x03(\t\x12\x18\n\x02le\x18\x15 \x03(\x0e\x32\x0c.ProductArea\x1a\x31\n\x07MeEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x15\n\x05value\x18\x02 \x01(\x0e\x32\x06.Enum2:\x02\x38\x01J\x04\x08\x03\x10\x13"\xdd\x01\n\x04User\x12\x0f\n\x02id\x18\x01 \x01(\x0b\x32\x03.ID\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x02o1\x18\x03 \x01(\x08H\x00\x12\x0c\n\x02o2\x18\t \x01(\tH\x00\x12\x0c\n\x02o3\x18\n \x01(\x03H\x00\x12\x0c\n\x02o4\x18\x0b \x01(\tH\x00\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12\x10\n\x08lastname\x18\x05 \x01(\t\x12\x0b\n\x03\x61ge\x18\x06 \x01(\x03\x12\x18\n\x02pa\x18\x07 \x01(\x0e\x32\x0c.ProductArea\x12\x14\n\x05\x63ode2\x18\x08 \x01(\x0b\x32\x05.Code\x12\x1a\n\x05\x65mail\x18\x14 \x01(\tR\x0b\x65mail_fieldB\x05\n\x03oo1"\xbe\x01\n\x07Product\x12\x0c\n\x04name\x18\x01 \x01(\t\x12+\n\nunit_price\x18\x02 \x03(\x0b\x32\x17.Product.UnitPriceEntry\x12\x13\n\x04\x63ode\x18\x03 \x01(\x0b\x32\x05.Code\x12\x1a\n\x04\x61rea\x18\x04 \x01(\x0e\x32\x0c.ProductArea\x12\x15\n\x05\x65num2\x18\x05 \x01(\x0e\x32\x06.Enum2\x1a\x30\n\x0eUnitPriceEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01"{\n\x0bRequisition\x12\x13\n\x04user\x18\x01 \x01(\x0b\x32\x05.User\x12\x13\n\x04\x63ode\x18\x02 \x01(\x0b\x32\x05.Code\x12\x19\n\x07product\x18\x03 \x01(\x0b\x32\x08.Product\x12\x10\n\x08quantity\x18\x04 \x01(\x05\x12\x15\n\x05\x65num2\x18\x05 \x01(\x0e\x32\x06.Enum2*.\n\x0bProductArea\x12\t\n\x05\x41rea1\x10\x00\x12\t\n\x05\x41rea2\x10\x01\x12\t\n\x05\x41rea3\x10\x02*\x17\n\x05\x45num2\x12\x06\n\x02\x65\x31\x10\x00\x12\x06\n\x02\x65\x32\x10\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "teste2_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CODE_MEENTRY"]._loaded_options = None
    _globals["_CODE_MEENTRY"]._serialized_options = b"8\001"
    _globals["_PRODUCT_UNITPRICEENTRY"]._loaded_options = None
    _globals["_PRODUCT_UNITPRICEENTRY"]._serialized_options = b"8\001"
    _globals["_PRODUCTAREA"]._serialized_start = 746
    _globals["_PRODUCTAREA"]._serialized_end = 792
    _globals["_ENUM2"]._serialized_start = 794
    _globals["_ENUM2"]._serialized_end = 817
    _globals["_ID"]._serialized_start = 16
    _globals["_ID"]._serialized_end = 32
    _globals["_CODE"]._serialized_start = 35
    _globals["_CODE"]._serialized_end = 202
    _globals["_CODE_MEENTRY"]._serialized_start = 147
    _globals["_CODE_MEENTRY"]._serialized_end = 196
    _globals["_USER"]._serialized_start = 205
    _globals["_USER"]._serialized_end = 426
    _globals["_PRODUCT"]._serialized_start = 429
    _globals["_PRODUCT"]._serialized_end = 619
    _globals["_PRODUCT_UNITPRICEENTRY"]._serialized_start = 571
    _globals["_PRODUCT_UNITPRICEENTRY"]._serialized_end = 619
    _globals["_REQUISITION"]._serialized_start = 621
    _globals["_REQUISITION"]._serialized_end = 744
# @@protoc_insertion_point(module_scope)
