# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: teste_full.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "teste_full.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10teste_full.proto\x12\nexample.v1"\x1e\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05"Q\n\x04User\x12\x0e\n\x02id\x18\x01 \x01(\x05\x42\x02\x18\x00\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x05\x65mail\x18\x03 \x01(\tH\x00\x12\x0f\n\x05phone\x18\x04 \x01(\tH\x00\x42\t\n\x07\x63ontact*/\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06\x41\x43TIVE\x10\x01\x12\x0c\n\x08INACTIVE\x10\x02\x32M\n\x0bUserService\x12\x39\n\x07GetUser\x12\x17.example.v1.UserRequest\x1a\x10.example.v1.User"\x03\x90\x02\x02\x1a\x03\x88\x02\x00\x42\x15\n\x13\x63om.example.user.v1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "teste_full_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"\n\023com.example.user.v1"
    _globals["_USER"].fields_by_name["id"]._loaded_options = None
    _globals["_USER"].fields_by_name["id"]._serialized_options = b"\030\000"
    _globals["_USERSERVICE"]._loaded_options = None
    _globals["_USERSERVICE"]._serialized_options = b"\210\002\000"
    _globals["_USERSERVICE"].methods_by_name["GetUser"]._loaded_options = None
    _globals["_USERSERVICE"].methods_by_name[
        "GetUser"
    ]._serialized_options = b"\220\002\002"
    _globals["_STATUS"]._serialized_start = 147
    _globals["_STATUS"]._serialized_end = 194
    _globals["_USERREQUEST"]._serialized_start = 32
    _globals["_USERREQUEST"]._serialized_end = 62
    _globals["_USER"]._serialized_start = 64
    _globals["_USER"]._serialized_end = 145
    _globals["_USERSERVICE"]._serialized_start = 196
    _globals["_USERSERVICE"]._serialized_end = 273
# @@protoc_insertion_point(module_scope)
