# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pack1/mod1.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'pack1/mod1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10pack1/mod1.proto\x12\x05pack1\"?\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1d\n\x04\x63ode\x18\x02 \x01(\x0e\x32\x0f.pack1.UserCode\x12\n\n\x02id\x18\x03 \x01(\t\"\x1a\n\tUserNames\x12\r\n\x05names\x18\x01 \x03(\t\"&\n\x08UserList\x12\x1a\n\x05users\x18\x01 \x03(\x0b\x32\x0b.pack1.User\"8\n\tUserInput\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1d\n\x04\x63ode\x18\x02 \x01(\x0e\x32\x0f.pack1.UserCode*\"\n\x08UserCode\x12\t\n\x05VALID\x10\x00\x12\x0b\n\x07INVALID\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pack1.mod1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERCODE']._serialized_start=218
  _globals['_USERCODE']._serialized_end=252
  _globals['_USER']._serialized_start=27
  _globals['_USER']._serialized_end=90
  _globals['_USERNAMES']._serialized_start=92
  _globals['_USERNAMES']._serialized_end=118
  _globals['_USERLIST']._serialized_start=120
  _globals['_USERLIST']._serialized_end=158
  _globals['_USERINPUT']._serialized_start=160
  _globals['_USERINPUT']._serialized_end=216
# @@protoc_insertion_point(module_scope)
