# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from pack1 import mod1_pb2 as pack1_dot_mod1__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pack2/mod2_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class user_serviceStub(object):
    """User Services
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.newuser = channel.unary_unary(
                '/pack2.user_service/newuser',
                request_serializer=pack1_dot_mod1__pb2.UserInput.SerializeToString,
                response_deserializer=pack1_dot_mod1__pb2.User.FromString,
                _registered_method=True)
        self.getusers = channel.unary_stream(
                '/pack2.user_service/getusers',
                request_serializer=pack1_dot_mod1__pb2.UserNames.SerializeToString,
                response_deserializer=pack1_dot_mod1__pb2.User.FromString,
                _registered_method=True)
        self.manynewuser = channel.stream_unary(
                '/pack2.user_service/manynewuser',
                request_serializer=pack1_dot_mod1__pb2.UserInput.SerializeToString,
                response_deserializer=pack1_dot_mod1__pb2.UserList.FromString,
                _registered_method=True)
        self.bilateralnewuser = channel.stream_stream(
                '/pack2.user_service/bilateralnewuser',
                request_serializer=pack1_dot_mod1__pb2.UserInput.SerializeToString,
                response_deserializer=pack1_dot_mod1__pb2.User.FromString,
                _registered_method=True)


class user_serviceServicer(object):
    """User Services
    """

    def newuser(self, request, context):
        """Make New User
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getusers(self, request, context):
        """get a list of users
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def manynewuser(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def bilateralnewuser(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_user_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'newuser': grpc.unary_unary_rpc_method_handler(
                    servicer.newuser,
                    request_deserializer=pack1_dot_mod1__pb2.UserInput.FromString,
                    response_serializer=pack1_dot_mod1__pb2.User.SerializeToString,
            ),
            'getusers': grpc.unary_stream_rpc_method_handler(
                    servicer.getusers,
                    request_deserializer=pack1_dot_mod1__pb2.UserNames.FromString,
                    response_serializer=pack1_dot_mod1__pb2.User.SerializeToString,
            ),
            'manynewuser': grpc.stream_unary_rpc_method_handler(
                    servicer.manynewuser,
                    request_deserializer=pack1_dot_mod1__pb2.UserInput.FromString,
                    response_serializer=pack1_dot_mod1__pb2.UserList.SerializeToString,
            ),
            'bilateralnewuser': grpc.stream_stream_rpc_method_handler(
                    servicer.bilateralnewuser,
                    request_deserializer=pack1_dot_mod1__pb2.UserInput.FromString,
                    response_serializer=pack1_dot_mod1__pb2.User.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pack2.user_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pack2.user_service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class user_service(object):
    """User Services
    """

    @staticmethod
    def newuser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pack2.user_service/newuser',
            pack1_dot_mod1__pb2.UserInput.SerializeToString,
            pack1_dot_mod1__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getusers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pack2.user_service/getusers',
            pack1_dot_mod1__pb2.UserNames.SerializeToString,
            pack1_dot_mod1__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def manynewuser(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/pack2.user_service/manynewuser',
            pack1_dot_mod1__pb2.UserInput.SerializeToString,
            pack1_dot_mod1__pb2.UserList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def bilateralnewuser(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/pack2.user_service/bilateralnewuser',
            pack1_dot_mod1__pb2.UserInput.SerializeToString,
            pack1_dot_mod1__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
